
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 18 09:10:14 ART 2019
//----------------------------------------------------

package Parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LPARENT = 7;
  public static final int RPARENT = 8;
  public static final int FORALL = 33;
  public static final int OWNS = 58;
  public static final int LBRACKET = 9;
  public static final int ASTERISK = 5;
  public static final int SLASH = 6;
  public static final int FRAME = 49;
  public static final int INTEGER = 44;
  public static final int INT = 19;
  public static final int INIT = 24;
  public static final int MINUS = 4;
  public static final int PRE = 29;
  public static final int SEMICOLON = 13;
  public static final int AND = 17;
  public static final int LT = 18;
  public static final int OR = 16;
  public static final int PRIMINT = 57;
  public static final int BOOL = 22;
  public static final int COMMA = 15;
  public static final int IMPLIES = 39;
  public static final int LOCK = 23;
  public static final int UNTIL = 37;
  public static final int PRIMBOOL = 56;
  public static final int NEXT = 35;
  public static final int PLUS = 3;
  public static final int MAIN = 27;
  public static final int DOT = 54;
  public static final int ID = 47;
  public static final int PROCESS = 25;
  public static final int EOF = 0;
  public static final int RBRACKET = 10;
  public static final int TRUE = 45;
  public static final int error = 1;
  public static final int SPEC = 2;
  public static final int NEQ = 42;
  public static final int GLOBAL = 28;
  public static final int GLOBALLY = 43;
  public static final int ACTION = 48;
  public static final int EQ = 41;
  public static final int INVARIANT = 31;
  public static final int OWN = 51;
  public static final int COLON = 14;
  public static final int NEG = 32;
  public static final int LBRACE = 11;
  public static final int POST = 30;
  public static final int WEAKUNTIL = 38;
  public static final int ENUM = 20;
  public static final int PRIMENUM = 21;
  public static final int PROPERTY = 52;
  public static final int RBRACE = 12;
  public static final int EXIST = 34;
  public static final int LTLPROPERTY = 53;
  public static final int AV = 50;
  public static final int USES = 26;
  public static final int FALSE = 46;
  public static final int RUN = 55;
  public static final int IFF = 40;
  public static final int FUTURE = 36;
}

