
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 21 18:00:51 ART 2017
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LPARENT = 7;
  public static final int RPARENT = 8;
  public static final int FORALL = 30;
  public static final int LBRACKET = 9;
  public static final int ASTERISK = 5;
  public static final int SLASH = 6;
  public static final int FRAME = 46;
  public static final int INTEGER = 41;
  public static final int INT = 19;
  public static final int INIT = 21;
  public static final int MINUS = 4;
  public static final int PRE = 26;
  public static final int SEMICOLON = 13;
  public static final int AND = 17;
  public static final int LT = 18;
  public static final int OR = 16;
  public static final int BOOL = 20;
  public static final int COMMA = 15;
  public static final int IMPLIES = 36;
  public static final int UNTIL = 34;
  public static final int NEXT = 32;
  public static final int PLUS = 3;
  public static final int MAIN = 24;
  public static final int DOT = 50;
  public static final int ID = 44;
  public static final int PROCESS = 22;
  public static final int EOF = 0;
  public static final int RBRACKET = 10;
  public static final int TRUE = 42;
  public static final int error = 1;
  public static final int SPEC = 2;
  public static final int NEQ = 39;
  public static final int GLOBAL = 25;
  public static final int GLOBALLY = 40;
  public static final int ACTION = 45;
  public static final int EQ = 38;
  public static final int INVARIANT = 28;
  public static final int OWN = 48;
  public static final int COLON = 14;
  public static final int NEG = 29;
  public static final int LBRACE = 11;
  public static final int POST = 27;
  public static final int WEAKUNTIL = 35;
  public static final int PROPERTY = 49;
  public static final int RBRACE = 12;
  public static final int EXIST = 31;
  public static final int AV = 47;
  public static final int USES = 23;
  public static final int FALSE = 43;
  public static final int IFF = 37;
  public static final int FUTURE = 33;
}

