
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 24 11:08:49 ART 2019
//----------------------------------------------------

package Parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int FORALL = 35;
  public static final int LPARENT = 7;
  public static final int RPARENT = 8;
  public static final int OWNS = 61;
  public static final int LBRACKET = 9;
  public static final int ASTERISK = 5;
  public static final int SLASH = 6;
  public static final int FRAME = 52;
  public static final int INTEGER = 46;
  public static final int INT = 19;
  public static final int INIT = 26;
  public static final int MINUS = 4;
  public static final int PRE = 31;
  public static final int SEMICOLON = 13;
  public static final int AND = 17;
  public static final int LT = 18;
  public static final int OR = 16;
  public static final int PRIMINT = 60;
  public static final int BOOL = 24;
  public static final int COMMA = 15;
  public static final int IMPLIES = 41;
  public static final int INC = 22;
  public static final int LOCK = 25;
  public static final int UNTIL = 39;
  public static final int PRIMBOOL = 59;
  public static final int ENUMCONS = 50;
  public static final int NEXT = 37;
  public static final int PLUS = 3;
  public static final int MAIN = 29;
  public static final int DOT = 57;
  public static final int ID = 49;
  public static final int PROCESS = 27;
  public static final int EOF = 0;
  public static final int RBRACKET = 10;
  public static final int TRUE = 47;
  public static final int error = 1;
  public static final int SPEC = 2;
  public static final int NEQ = 44;
  public static final int GLOBAL = 30;
  public static final int GLOBALLY = 45;
  public static final int ACTION = 51;
  public static final int EQ = 43;
  public static final int INVARIANT = 33;
  public static final int OWN = 54;
  public static final int COLON = 14;
  public static final int NEG = 34;
  public static final int LBRACE = 11;
  public static final int POST = 32;
  public static final int WEAKUNTIL = 40;
  public static final int ENUM = 20;
  public static final int PRIMENUM = 21;
  public static final int PROPERTY = 55;
  public static final int RBRACE = 12;
  public static final int EXIST = 36;
  public static final int LTLPROPERTY = 56;
  public static final int AV = 53;
  public static final int USES = 28;
  public static final int DEC = 23;
  public static final int FALSE = 48;
  public static final int RUN = 58;
  public static final int IFF = 42;
  public static final int FUTURE = 38;
}

